name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Allows manual triggering from the Actions tab

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # Use documented inputs
        android: true
        dotnet: true
        haskell: true
        large-packages: true # Attempts to remove large apt packages
        docker-images: true  # Keep this if docker is used or potentially pre-installed
        tool-cache: false    # Usually set to false unless specific tool cache cleaning needed
        swap-storage: true   # Correct name for swap file removal
        
    - name: Install hatch and coverage
      run: |
        python -m pip install --upgrade pip --no-cache-dir
        pip install hatch coverage --no-cache-dir
    
    - name: Run tests with coverage run
      # Run tests using 'coverage run' managed by hatch environment
      # Pass arguments like timeout/no-xdist directly to pytest
      run: hatch run test:coverage run -m pytest --timeout=120 -p no:xdist tests/
    
    - name: Combine coverage data (if needed)
      # Important if tests were run in parallel, harmless otherwise
      run: hatch run coverage combine || true
    
    - name: Generate coverage XML report
      # Use hatch to run coverage in the correct environment
      run: hatch run coverage xml -o coverage.xml
    
    - name: Generate coverage report summary
      # Display summary in the logs
      run: hatch run coverage report -m
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml # Should exist now
        fail_ci_if_error: true 